#!/usr/bin/env python3
"""Generate one page stub per entry: data/sites/<id>.yml -> entries/<id>.md.

Stubs are tiny committed front-matter files; the `entry` layout renders
everything from site.data.sites[<id>] at build time. Removes stubs whose
entry is gone. Idempotent. Run after entries change:  python3 scripts/gen-pages.py

(menowise homes no page generator in the records adapter — entries render via
this project-local step, kept in the repo and re-runnable by hand or CI.)
"""
from __future__ import annotations

import json
import pathlib

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
ENTRIES = ROOT / "data" / "sites"
STUBS = ROOT / "entries"

STUBS.mkdir(exist_ok=True)
records = {}
for path in sorted(ENTRIES.glob("*.yml")) if ENTRIES.is_dir() else []:
    doc = yaml.safe_load(path.read_text(encoding="utf-8"))
    records[path.stem] = doc

changed = 0
for rid, rec in records.items():
    stub = STUBS / f"{rid}.md"
    body = (
        "---\n"
        "# GENERATED by scripts/gen-pages.py from data/sites/ — do not hand-edit.\n"
        "layout: entry\n"
        f"entry_id: {rid}\n"
        f"title: {json.dumps(rec.get('title', rid))}\n"
        f"permalink: /entries/{rid}/\n"
        "---\n"
    )
    if not stub.is_file() or stub.read_text(encoding="utf-8") != body:
        stub.write_text(body, encoding="utf-8")
        changed += 1

# drop stubs whose entry is gone (keep entries/index.md)
for stub in STUBS.glob("*.md"):
    if stub.stem != "index" and stub.stem not in records:
        stub.unlink()
        changed += 1

print(f"gen-pages: {len(records)} entries, {changed} stub(s) changed")
